#!/bin/bash
#
# config: 2 20
# @brief: Get the data from all the virutal EEPROMs installed on the device.
#

. $DREPORT_INCLUDE/functions

file_name="eepromdata.log"

eeprom_files=$(ls /sys/bus/i2c/devices/*/slave-eeprom)

for eeprom_file in $eeprom_files; do
    desc="$eeprom_file data"
    command="echo $ hexdump $eeprom_file; hexdump $eeprom_file; echo '';"
    add_cmd_output "$command" "$file_name" "$desc"
done
