#!/bin/bash
#
# config: 2 20
# @brief: Get output of the lsof command.
#

. $DREPORT_INCLUDE/functions

file_name="lsof.log"
desc="lsof command output"
command="lsof"

add_cmd_output "$command" "$file_name" "$desc"

