#!/bin/bash
#
# config: 2 20
# @brief: Get the mctp dbus information.
#

. $DREPORT_INCLUDE/functions

file_name="mctpdbusinfo.log"

# Get the current MCTP Control D-Bus services
array=(`busctl | grep MCTP.Control | awk '{print $1}' | tr "\n" " "`)

if [ ${#array[@]} -eq 0 ]; then
    log_error "Failed to collect any mctp dbus information"
    exit 1
fi

for i in "${array[@]}"; do
    name=$(echo $i | cut -d "." -f 5)

    desc="mctp $name dbus tree"
    command="busctl tree $i"
    add_cmd_output "$command" "$file_name" "$desc"

    desc="mctp $name dbus objects"
    command="busctl call --verbose --no-pager $i \
                    /xyz/openbmc_project/mctp \
                    org.freedesktop.DBus.ObjectManager \
                    GetManagedObjects"
    add_cmd_output "$command" "$file_name" "$desc"
done
