#!/usr/bin/env bash
#
# config: 2 20
# @brief: MCTP network information
#

. $DREPORT_INCLUDE/functions

out_file_name="mctp-network.log"
desc="MCTP Network"
command="echo 'MCTP Network:'; echo '';"

add_cmd_output "$command" "$out_file_name" "$desc"

add_cmd_output "mctp link" "$out_file_name" "mctp link"
add_cmd_output "mctp addr" "$out_file_name" "mctp addr"
add_cmd_output "mctp route" "$out_file_name" "mctp route"
