#!/bin/bash
#
# config: 2 20
# @brief: Get the list of pcie devices.
#

. $DREPORT_INCLUDE/functions

desc="pcie device list"

command="ls /sys/bus/pci/devices"

file_name="pciedevicelist.log"

if [ -z "$($command 2>/dev/null)" ]; then
    echo "No PCIe devices present on this platform" >> "$name_dir/$file_name"
    log_info "No PCIe devices found, skipping $desc"
else
    add_cmd_output "$command" "$file_name" "$desc"
fi