#!/bin/bash
#
# config: 2 20
# @brief: Get the pldm dbus information.
#

. $DREPORT_INCLUDE/functions

desc="pldm dbus objects"

command="busctl call --verbose --no-pager \
                xyz.openbmc_project.PLDM \
                / \
                org.freedesktop.DBus.ObjectManager \
                GetManagedObjects"

file_name="pldmdbusinfo.log"

add_cmd_output "$command" "$file_name" "$desc"