#!/bin/bash
#
# config: 2 20
# @brief: Get the spdm dbus information.
#

. $DREPORT_INCLUDE/functions

desc="spdm dbus objects"

command="busctl call --verbose --no-pager \
                xyz.openbmc_project.SPDM \
                /xyz/openbmc_project/SPDM \
                org.freedesktop.DBus.ObjectManager \
                GetManagedObjects"

file_name="spdmdbusinfo.log"

add_cmd_output "$command" "$file_name" "$desc"