#!/bin/bash
#
# config: 2 20
# @brief: Get the pcie aer for hgx.
#

. $DREPORT_INCLUDE/functions

desc="hgx pcie aer"

command="lspci"

file_name="hgxpcieaer.log"

add_cmd_output "$command" "$file_name" "$desc"