#!/bin/bash
#
# config: 2 20
# @brief: Get the retimer boot status for hgx.
#

. $DREPORT_INCLUDE/functions

desc="hgx retimer boot status"

command="i2cdetect -y -q 3"

file_name="hgxretimerbootstatus.log"

add_cmd_output "$command" "$file_name" "$desc"