#!/bin/bash
#
# config: 2 20
# @brief: Get the HSC alert cached/previously reported data
#

. $DREPORT_INCLUDE/functions

desc="HGX HSC alert cached/previously reported data"
file_name="/tmp/hsc_alert_wrapper_cache"

add_copy_file "$file_name" "$desc"
