#!/bin/bash
#
# config: 2 20
# @brief: Get the list of vfio devices.
#

. $DREPORT_INCLUDE/functions

desc="vfio device list"

command="ls /dev/vfio"

file_name="vfiodevicelist.log"

add_cmd_output "$command" "$file_name" "$desc"